<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Dashboard extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        if ($this->session->userdata("id") != null) {
            $id_pengguna = $this->session->userdata("id");
        } else {
            redirect('pengguna/login');
        }
    }

    function index()
    {
        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main', $data);
    }
}
