<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Claim_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get claim by id
     */
    function get_claim($id)
    {
        return $this->db->get_where('claim', array('id' => $id))->row_array();
    }

    /*
     * Get all claim
     */
    function get_all_claim()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('claim')->result_array();
    }

    function get_all_claim_v2()
    {
        $id_pengguna = $this->getIdPengguna();
        $query = "select c.*, p.nama  as namaCleint, p2.nama  as namaInspector from claim c 
        inner join pengguna p on c.id_pengguna  = p.id
        LEFT  join pengguna p2 on c.id_investigasi  = p2.id 
        where p.id = $id_pengguna
        ";

        $data = $this->tampilData($query);
        return $data;
    }

    function get_all_claim_v3_member($status)
    {
        $id_pengguna = $this->getIdPengguna();
        $query = "select c.*, p.nama  as namaCleint, p2.nama  as namaInspector from claim c 
        inner join pengguna p on c.id_pengguna  = p.id
        LEFT  join pengguna p2 on c.id_investigasi  = p2.id 
        where p.id = $id_pengguna
        and c.status_claim = $status
        ";

        $data = $this->tampilData($query);
        return $data;
    }

    function get_all_claim_v3_inspector($status)
    {
        $id_pengguna = $this->getIdPengguna();
        $query = "select c.*, p.nama  as namaCleint, p2.nama  as namaInspector from claim c 
        inner join pengguna p on c.id_pengguna  = p.id
        LEFT  join pengguna p2 on c.id_investigasi  = p2.id 
        where c.id_investigasi = $id_pengguna
        and c.status_claim = $status
        ";

        $data = $this->tampilData($query);
        return $data;
    }


    function get_all_claim_v3_admin($status)
    {
        $query = "select c.*, p.nama  as namaCleint, p2.nama  as namaInspector from claim c 
        inner join pengguna p on c.id_pengguna  = p.id
        LEFT  join pengguna p2 on c.id_investigasi  = p2.id 
        where c.status_claim = $status
        ";

        $data = $this->tampilData($query);
        return $data;
    }
    /*
     * function to add new claim
     */
    function add_claim($params)
    {
        $this->db->insert('claim', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update claim
     */
    function update_claim($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('claim', $params);
    }

    /*
     * function to delete claim
     */
    function delete_claim($id)
    {
        return $this->db->delete('claim', array('id' => $id));
    }


    function tampilData($query)
    {
        return $this->db->query($query)->result_array();
    }

    function execQuery($query)
    {
        return $this->db->query($query);
    }

    function getOneValue($query)
    {
        return $this->db->query($query)->row();
    }

    function getIdPengguna()
    {
        $id_pengguna = $this->session->userdata("id");
        return $id_pengguna;
    }
}
