<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Pengguna_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get pengguna by id
     */
    function get_pengguna($id)
    {
        return $this->db->get_where('pengguna', array('id' => $id))->row_array();
    }

    /*
     * Get all pengguna
     */
    function get_all_pengguna()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('pengguna')->result_array();
    }

    function get_all_investigator()
    {
        $query = "select * from pengguna where role = 2";
        $data = $this->tampilData($query);
        return $data;
    }

    /*
     * function to add new pengguna
     */
    function add_pengguna($params)
    {
        $this->db->insert('pengguna', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update pengguna
     */
    function update_pengguna($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('pengguna', $params);
    }

    /*
     * function to delete pengguna
     */
    function delete_pengguna($id)
    {
        return $this->db->delete('pengguna', array('id' => $id));
    }

    function tampilData($query)
    {
        return $this->db->query($query)->result_array();
    }

    function execQuery($query)
    {
        return $this->db->query($query);
    }

    function getOneValue($query)
    {
        return $this->db->query($query)->row();
    }
}
