<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Universal_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function cek_data($table, $where)
    {
        return $this->db->get_where($table, $where);
    }

    function cekJumlahRecord($query)
    {
        $cek = $this->db->query($query)->num_rows();
        return $cek;
    }

    function tampilData($query)
    {
        return $this->db->query($query)->result_array();
    }

    function execQuery($query)
    {
        return $this->db->query($query);
    }

    function getOneValue($query)
    {
        return $this->db->query($query)->row();
    }
}
